version: '3.7'
services:

  #PostgreSQL Service
  laravel-pgsql:
    image: postgres:12.0-alpine
    container_name: laravel-pgsql
    working_dir: /data/pgsql
    volumes:
      - ../postgresql-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: tdduser
      POSTGRES_PASSWORD: tdduser123
      POSTGRES_DB: pgdb
    ports:
      - "5432:5432"
    networks:
      - dev

  # PHP Service
  tdd-app:
    build: ../docker/php/.
    container_name: tdd-app
    networks:
      - dev
    volumes:
      - ./app:/app
    ports:
      - "8000:8000"
    depends_on:
      - laravel-pgsql

#Docker Networks
networks:
  dev:
    driver: bridge